controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        if (jump < 1) {
            mySprite.vy = -100
            jump += 1
        }
    }
})
function vampire () {
    tiles.setTilemap(tilemap`level2`)
}
let jump = 0
let mySprite: Sprite = null
scene.setBackgroundImage(img`
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccdddddddddddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccdddddddddddddddddddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccdddddddddddddddddddddddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccdddddddddddddddddddddddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccdddddddddddddddddddddddddddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccdddddddddddddddddddddddddddddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffffffffcccccccccccccccccccccccccccc
    cccccccccdddddddddddddddddddddddddddddddddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffccccccccccccccccccccccccccc
    cccccccccdddddddddddddddddddddddddddddddddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffccccccccccccccccccccccccccc
    ccccccccdddddddddddddddddddddddddddddddddddcccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffffffffcccccccfffffffffffffffffcccccccccccccccccccccccccc
    cccccccdddddddddddddddddddddddddddddddddddddccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffcccccccccccccccccccccccccc
    ccccccdddddddddddddddddddddddddddfffffffffffdccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccc
    ccccccdddddddddddddddddddddddfffffffffffffffffccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccc
    cccccdddddddddddddddddddddddfffffffffffffffffffcccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccc
    cccccddddddddddddddddddddddffffffffffffffffffffffffffffccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccc
    cccccdddddddddddddddddddddfffffffffffffffffffffffffffffffffccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccc
    ccccddddddddddddddddddddddfffffffffffffffffffffffffffffffffffccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccc
    ccccdddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccc
    ccccdddddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccc
    ccccddddddddddddddddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccc
    ccccddddddddddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccc
    ccccddddddddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccc
    ccccddddddddddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccc
    ccccdddddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccc
    ccccdddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccc
    ccccddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccc
    ccccddddddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccccc
    ccccdddddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccc
    ccccdddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccccccc
    cccccdddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccccccccc
    cccccdddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccc
    cccccddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccccccccc
    ccccccdddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccc
    ccccccdddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccccccc
    cccccccddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccc
    ccccccccdddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccc
    cccccccccddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccc
    cccccccccddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccc
    ccccccccccdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccc
    ccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccc
    cccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccc
    ccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccc
    cccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccc
    cccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccc
    cccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccc
    ccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccc
    ccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccc
    ccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccc
    ccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccc
    ccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffcccccc
    ccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffcccfffffffffffffffffffffffffffffffffffffffffffffffffcccccc
    cccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccffffffffffffffffffcccccffffffffffffffffffffffffffffffffffffffffffffffffccccc
    cccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccffffffffffffffffffcccccccffffffffffffffffffffffffffffffffffffffffffffffccccc
    ccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccffffffffffffffffffccccccccccccffffffffffffffffffffffffffffffffffffffffffcccc
    cccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccffffffffffffffffffcccccccccccfffffffffffffffffffffffffffffffffffffffffffcccc
    cccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccffffffffffffffffffcccccccccccfffffffffffffffffffffffffffffffffffffffffffcccc
    ccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccffffffffffffffffffccccccccccffffffffffffffffffffffffffffffffffffffffffffcccc
    cccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccffffffffffffffffffccccccccccffffffffffffffffffffffffffffffffffffffffffffcccc
    cccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffffffffcccc
    ccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffffffffcccc
    cccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccffffffffffffffffffcccccccccffffffffffffffffffffffffffffffffffffffffffffffccc
    cccccccccccccccccffffffffffffffffffffffffffffffffffffcccccccccffffffffffffffccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffffffffffcc
    ccccccccccccccccccccfffffffffffffffffffffffffffffffffcccccccccccffffffccccccccccccccffffffffffffffffffccccccccccfffffffffffffffffffffffffffffffffffffffffffffffc
    ccccccccccccccccccccfffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    cccccccccccccccccccffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    cccccccccccccccccccffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    cccccccccccccccccccffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    cccccccccccccccccccffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    ccccccccccccccccccccfffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    ccccccccccccccccccccfffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    cccccccccccccccccccccccffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffcccccccccc
    cccccccccccccccccccccccccccccccccffffffffffffffffffffcccccccccccccccccccccccccccccccffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffcccccccccc
    cccccccccccccccccccccccccccccccccffffffffffffffffffffccccccccccccccccccccccccccccccfffffffffffffffffffccccccccccffffffffffffffffffffffffffffffffffffffcccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffccccccccccccccccccccccccccccccffffffffffffffffffccccccccccccfffffffffffffffffffffffffffffffffffffcccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffccccccccccccccccccccccccccccccffffffffffffffffffccccccccccccfffffffffffffffffffffffffffffffffffffcccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffccccccccccccccccccccccccccccccffffffffffffffffffcccccccccccccffffffffffffffffffffffffffffffffffffcccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffccccccccccccccccccccccccccccccffffffffffffffffffcccccccccccccccccffffffffffffffffffffffffffffffffcccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffccccccccccccccccccccccccccccccffffffffffffffffffcccccccccccccccccffffffffffffffffffffffffffffffffcccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffccccccccccccccccccccccccccccccffffffffffffffffffcccccccccccccccccfffffffffffffffffffffffffffffffccccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffccccccccccccccccccccccccccccccffffffffffffffffffccccccccccccccccccffffffffffffffffffffffffffffffccccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffccccccccccccccccccccccccccccccffffffffffffffffffcccccccccccccccccccfffffffffffffffffffffffffffffccccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffccccccccccccccccccccffffffffffffffffffffffffffffccccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffccccccccccccccccccccccccccccccffffffffffffffffffccccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffcccccccccccccccccccccccccccccccfffffffffffffffffccccccccccc
    ccccccccccccccccccccccccccccccccfffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffccccccccccccccccccccccccccccccccffffffffffffffffccccccccccc
    cccccccccccccccccccccccccccccccffffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffcccccccccccccccccccccccccccccccccfffffffffffffffccccccccccc
    cccccccccccccccccccccccccccccccffffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffccccccccccccccccccccccccccccccccccffffffffffffffccccccccccc
    cccccccccccccccccccccccccccccccffffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffccccccccccccccccccccccccccccccccccccfffffffffffcccccccccccc
    cccccccccccccccccccccccccccccccffffffffffffffffffffffcccccccccccccccccccccccccccccfffffffffffffffffffcccccccccccccccccccccccccccccccccccccffffffffffcccccccccccc
    cccccccccccccccccccccccccccccccffffffffffffffffffffffccccccccccccccccccccccccccccffffffffffffffffffffcccccccccccccccccccccccccccccccccccccffffffffffcccccccccccc
    cccccccccccccccccccccccccccccccffffffffffffffffffffffccccccccccccccccccccccccccccffffffffffffffffffffcccccccccccccccccccccccccccccccccccccffffffffffcccccccccccc
    cccccccccccccccccccccccccccccccffffffffffffffffffffffccccccccccccccccccccccccccccffffffffffffffffffffcccccccccccccccccccccccccccccccccccccffffffffffcccccccccccc
    cccccccccccccccccccccccccccccccffffffffffffffffffffffcccccccccccccccccccccccccccfffffffffffffffffffffcccccccccccccccccccccccccccccccccccccffffffffffcccccccccccc
    cccccccccccccccccccccccccccccccffffffffffffffffffffffcccccccccccccccccccccccccccfffffffffffffffffffffcccccccccccccccccccccccccccccccccccccffffffffffcccccccccccc
    ccccccccccccccccccccccccccccccfffffffffffffffffffffffcccccccccccccccccccccccccccfffffffffffffffffffffcccccccccccccccccccccccccccccccccccccffffffffffcccccccccccc
    ccccccccccccccccccccccccccccccfffffffffffffffffffffffccccccccccccccccccccccccccffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccffffffffffcccccccccccc
    ccccccccccccccccccccccccccccccffffffffffffffffffffffffcccccccccccccccccccccccccffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccffffffffffcccccccccccc
    cccccccccccccccccccccccccccccfffffffffffffffffffffffffcccccccccccccccccccccccccffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccffffffffffcccccccccccc
    ccccccccccccccccccccccccccccffffffffffffffffffffffffffcccccccccccccccccccccccccfffffffffffffffffffffffccccccccccccccccccccccccccccccccccccfffffffffffccccccccccc
    cccccccccccccccccccccccccccfffffffffffffffffffffffffffcccccccccccccccccccccccccfffffffffffffffffffffffccccccccccccccccccccccccccccccccccccfffffffffffccccccccccc
    cccccccccccccccccccccccccccfffffffffffffffffffffffffffcccccccccccccccccccccccccfffffffffffffffffffffffccccccccccccccccccccccccccccccccccccfffffffffffccccccccccc
    ccccccccccccccccccccccccccffffffffffffffffffffffffffffcccccccccccccccccccccccccfffffffffffffffffffffffcccccccccccccccccccccccccccccccccccfffffffffffffcccccccccc
    cccccccccccccccccccccccccfffffffffffffffffffffffffffffcccccccccccccccccccccccccfffffffffffffffffffffffcccccccccccccccccccccccccccccccccccfffffffffffffcccccccccc
    ccccccccccccccccccccccccffffffffffffffffffffffffffffffcccccccccccccccccccccccccffffffffffffffffffffffffccccccccccccccccccccccccccccccccccffffffffffffffccccccccc
    cccccccccccccccccccccccfffffffffffffffffffffffffffffffcccccccccccccccccccccccccffffffffffffffffffffffffccccccccccccccccccccccccccccccccccffffffffffffffccccccccc
    ccccccccccccccccccccccfffffffffffffffffffffffffffffffffccccccccccccccccccccccccffffffffffffffffffffffffcccccccccccccccccccccccccccccccccfffffffffffffffccccccccc
    ccccccccccccccccccccccfffffffffffffffffffffffffffffffffccccccccccccccccccccccccfffffffffffffffffffffffffccccccccccccccccccccccccccccccccfffffffffffffffccccccccc
    cccccccccccccccccccccfffffffffffffffffffffffffffffffffffccccccccccccccccccccccfffffffffffffffffffffffffffccccccccccccccccccccccccccccccfffffffffffffffffcccccccc
    ccccccccccccccccccccffffffffffffffffffffffffffffffffffffcccccccccccccccccccccffffffffffffffffffffffffffffcccccccccccccccccccccccccccccffffffffffffffffffcccccccc
    ccccccccccccccccccccfffffffffffffffffffffffffffffffffffffccccccccccccccccccccfffffffffffffffffffffffffffffccccccccccccccccccccccccccccfffffffffffffffffffccccccc
    cccccccccccccccccccffffffffffffffffffffffffffffffffffffffcccccccccccccccccccfffffffffffffffffffffffffffffffccccccccccccccccccccccccccffffffffffffffffffffccccccc
    ccccccccccccccccccfffffffffffffffffffffffffffffffffffffffccccccccccccccccccfffffffffffffffffffffffffffffffffccccccccccccccccccccccccfffffffffffffffffffffccccccc
    cccccccccccccccccfffffffffffffffffffffffffffffffffffffffffcccccccccccccccfffffffffffffffffffffffffffffffffffffccccccccccccccccccccccffffffffffffffffffffffcccccc
    ccccccccccccccccffffffffffffffffffffffffffffffffffffffffffcccccccccccccffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccffffffffffffffffffffffffccccc
    cccccccccccccccffffffffffffffffffffffffffffffffffffffffffffcccccccccfffffffffffffffffffffffffffffffffffffffffffffccccccccccccccffffffffffffffffffffffffffffccccc
    ccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccc
    ccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc
    ccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc
    `)
game.showLongText("vampire hunter", DialogLayout.Bottom)
mySprite = sprites.create(img`
    . . . . . . . . . . . . . 
    . . . f f f f f f . . . . 
    . f f f f f f f f f . . . 
    . f f f f f f c f f f . . 
    f f f f c f f f c f f f . 
    f c f f c c f f f c c f f 
    f c c f f f f e f f f f f 
    f f f f f f f e e f f f . 
    f f e e f b f e e f f f . 
    f f e 4 e 1 f 4 4 f f . . 
    . f f f e 4 4 4 4 f . . . 
    . 4 4 4 e e e e f f . . . 
    . e 4 4 e 7 7 7 7 f . . . 
    . f e e f 6 6 6 6 f f . . 
    . f f f f f f f f f f . . 
    . . f f . . . f f f . . . 
    `, SpriteKind.Player)
forever(function () {
    mySprite.ay = 200
})
